Share_Box/config/routes.rb
Rails.application.routes.draw do
  resources :folders
  resources :assets
  devise_for :users

  match "assets/get/:id" => "assets#get", as: "download",via: [:get]

  match "browse/:folder_id" => "home#browse", as: "browse",via: [:get]
  match "browse/:folder_id/new_folder" => "folders#new", as: "new_sub_folder",via: [:get,:post]
  match "browse/:folder_id/new_file" => "assets#new", :as => "new_sub_file",via: [:get,:post]

  #for renaming a folder
  match "browse/:folder_id/rename" => "folders#edit", :as => "rename_folder",via: [:get,:put]

  #for sharing the folder
  match "home/share" => "home#share",via: [:post]

  root :to => "home#index"
end

Share_Box/app/models/asset.rb
class Asset < ActiveRecord::Base
  belongs_to :user
  belongs_to :folder
  #attr_accessor :uploaded_file

  has_attached_file :uploaded_file

  validates_attachment_size :uploaded_file, :less_than => 10.megabytes
  validates_attachment_presence :uploaded_file
  validates_attachment_content_type :uploaded_file, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  has_attached_file :uploaded_file, url: "/assets/get/:id", path: ":Rails_root/assets/:id/:basename.:extension"


  def file_name
    uploaded_file_file_name
  end

  def file_size
    uploaded_file_file_size
  end


end

Share_Box/app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  before_action :set_asset, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /assets
  # GET /assets.json
  def index
    @assets = current_user.assets
  end

  # GET /assets/1
  # GET /assets/1.json
  def show
  end

  # GET /assets/new
  def new
    @asset = current_user.assets.build

    if params[:folder_id]
      @current_folder = current_user.folders.find(params[:folder_id])
      @asset.folder_id = @current_folder.id
    end
  end

  # GET /assets/1/edit
  def edit
  end

  # POST /assets
  # POST /assets.json
  def create
    @asset = current_user.assets.new(asset_params)

    if @asset.save
      flash[:notice] = "Successfully uploaded the file."
      if @asset.folder
        redirect_to browse_path(@asset.folder)
      else
        redirect_to root_url
      end
    else
      render :action => 'new'
    end
  end

  # PATCH/PUT /assets/1
  # PATCH/PUT /assets/1.json
  def update
    respond_to do |format|
      if @asset.update(asset_params)
        format.html { redirect_to @asset, notice: 'Asset was successfully updated.' }
        format.json { render :show, status: :ok, location: @asset }
      else
        format.html { render :edit }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assets/1
  # DELETE /assets/1.json
  def destroy
    @parent_folder = @asset.folder
    @asset.destroy
    flash[:notice] = "Successfully deleted the file."

    if @parent_folder
      redirect_to browse_path(@parent_folder)
    else
      redirect_to root_url
    end
  end

  def get
    asset = current_user.assets.find(params[:id])
    if asset
      send_file asset.uploaded_file.path,:type => asset.uploaded_file_content_type
    else
      flash[:error] = "Don't be cheeky! Mind your own assets!"
      redirect_to assets_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asset
      @asset = current_user.assets.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def asset_params
      params.require(:asset).permit(:uploaded_file,:folder_id)
    end
end

Share_Box/app/helpers/assets_helper.rb
module AssetsHelper
end

Share_Box/app/views/assets/_form.html.erb
<%= form_for(@asset) do |f| %>
  <% if @asset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asset.errors.count, "error") %> prohibited this asset from being saved:</h2>

      <ul>
      <% @asset.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uploaded_file, "File" %><br />
    <%= f.file_field :uploaded_file %>
  </div>
    <div class="field">
      <%= f.hidden_field :folder_id %>
    </div>
  <div class="actions">
    <%= f.submit 'Upload'%>
  </div>
<% end %>

Share_Box/app/views/assets/edit.html.erb
<h1>Editing Asset</h1>

<%= render 'form' %>

<%= link_to 'Show', @asset %> |
<%= link_to 'Back', assets_path %>

Share_Box/app/views/assets/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Assets</h1>

<table>
  <tr>
    <th>Uploaded Files</th>
  </tr>
  <% for asset in @assets %>
      <tr>
        <td><%= link_to asset.file_name, download_url(asset)%></td>
        <td><%= link_to "Show", asset %></td>
        <td><%= link_to "Edit", edit_asset_path(asset) %></td>
        <td><%= link_to "Destroy", asset, :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
  <% end %>
</table>
<p><%= link_to "New Asset", new_asset_path %></p>

Share_Box/app/views/assets/new.html.erb
<h1>Upload a file</h1>
<%= render :partial => "home/breadcrumbs" %>

<%= render 'form' %>

<p>
  <% if @asset.folder %>
      <%= link_to "Back to '#{@asset.folder.name}' Folder", browse_path(@asset.folder) %>
  <% else %>
      <%= link_to "Back", root_url %>
  <% end %>
</p>

Share_Box/app/views/assets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @asset.user_id %>
</p>

<%= link_to 'Edit', edit_asset_path(@asset) %> |
<%= link_to 'Back', assets_path %>