Share_Box/config/routes.rb
Rails.application.routes.draw do
  resources :folders
  resources :assets
  devise_for :users

  match "assets/get/:id" => "assets#get", as: "download",via: [:get]

  match "browse/:folder_id" => "home#browse", as: "browse",via: [:get]
  match "browse/:folder_id/new_folder" => "folders#new", as: "new_sub_folder",via: [:get,:post]
  match "browse/:folder_id/new_file" => "assets#new", :as => "new_sub_file",via: [:get,:post]

  #for renaming a folder
  match "browse/:folder_id/rename" => "folders#edit", :as => "rename_folder",via: [:get,:put]

  #for sharing the folder
  match "home/share" => "home#share",via: [:post]

  root :to => "home#index"
end

Share_Box/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      #load current_user's folders
      @folders = current_user.folders.roots

      #load current_user's files(assets)
      @assets = current_user.assets.where("folder_id is NULL").order("uploaded_file_file_name desc")
    end
  end

  def browse
    @current_folder = current_user.folders.find(params[:folder_id])
    if @current_folder
      @folders = @current_folder.children
      @assets = @current_folder.assets.order("uploaded_file_file_name desc")

      render action: 'index'
    else
      flash[:error] = "Don't be cheeky! Mind your own folders!"
      redirect_to root_url
    end
  end

  def share
    email_addresses = params[:email_addresses].split(",")

    email_addresses.each do |email_address|
      @shared_folder = current_user.shared_folders.new
      @shared_folder.folder_id = params[:folder_id]
      @shared_folder.shared_email = email_address

      shared_user = User.find_by_email(email_address)
      @shared_folder.shared_user_id = shared_user.id if shared_user
      @shared_folder.message = params[:message]
      @shared_folder.save

      UserMailer.invitation_to_share(@shared_folder).deliver_now
    end
    respond_to do |format|
      format.js {
      }
    end
  end
end

Share_Box/app/helpers/home_helper.rb
module HomeHelper
end

Share_Box/app/views/home/_breadcrumbs.html.erb
<div class="breadcrumbs">
  <% if @current_folder #checking if we are under any folder %>
      <%= link_to "ShareBox", root_url %>
      <% @current_folder.ancestors.reverse.each do |folder| %>
          » <%= link_to folder.name, browse_path(folder) %>
      <% end %>
      »  <%= @current_folder.name %>
  <% else #if we are not under any folder%>
      ShareBox
  <% end %>
</div>

Share_Box/app/views/home/index.html.erb
<% unless user_signed_in? %>
    <h1>Welcome to ShareBox</h1>
    <p>File sharing web application you can't ignore.</p>

<% else %>
    <div id="menu">
      <ul id= "top_menu">
        <% if @current_folder %>
            <li><%= link_to "Upload", new_sub_file_path(@current_folder) %></li>
            <li><%= link_to "New Folder", new_sub_folder_path(@current_folder) %></li>
        <% else %>
            <li><%= link_to "Upload", new_asset_path %></li>
            <li><%= link_to "New Folder", new_folder_path %></li>
        <% end %>
      </ul>
    </div>

    <%= render :partial => "breadcrumbs" %>

    <div class="asset_list_header">
      <div class="file_name_header">File Name</div>
      <div class="file_size_header">Size</div>
      <div class="file_last_updated_header">Modified</div>
    </div>

    <div class="asset_list">

      <% @folders.each do |folder| %>
          <div class="asset_details <%= folder.shared? ? 'shared_folder' : 'folder' %>" id="folder_<%= folder.id %>">
          <div class="file_name"><%= link_to folder.name, browse_path(folder) %></div>
            <div class="file_size"> - </div>
            <div class="file_last_updated"> - </div>
            <div class="actions">
              <div class="share">
                <%= link_to "Share", "#", :folder_id => folder.id, :folder_name => folder.name %>
              </div>
              <div class="rename">
                <%= link_to "Rename",rename_folder_path(folder) %>
              </div>
              <div class="delete">
                <%= link_to "Delete", folder, method: :delete,data: { confirm: 'Are you sure?' }%>
              </div>
            </div>

          </div>
      <% end %>

      <% @assets.each do |asset| %>
          <div class="asset_details file">
            <div class="file_name"><%= link_to asset.file_name, download_url(asset) %></div>
            <div class="file_size"><%= number_to_human_size(asset.file_size, :precision => 2) %></div>
            <div class="file_last_updated"><%= asset.uploaded_file_updated_at %></div>

            <div class="actions">
              <div class="download">
                <%= link_to "Download",download_url(asset) %>
              </div>
              <div class="delete">
                <%= link_to "Delete", asset, method: :delete,data: { confirm: 'Are you sure?' }%>
              </div>
            </div>
          </div>
      <% end %>
    </div>

<% end %>

<div id="invitation_form" title="Invite others to share" style="display:none">
  <form action="/home/share">
    <label for="email_addresses">Enter recipient email addresses here</label>
    <input type="text" id="email_addresses" name="email_addresses" class = 'text ui-widget-content ui-corner-all'><br>
    <label for="message">Message</label><br>
    <textarea id="message" name="message"> </textarea>
    <input type="hidden" id="folder_id" name="folder_id">
  </form>
</div>

Share_Box/app/views/home/share.js.erb
//closing the dialog box
$("#invitation_form").dialog("close");

//making sure we don't display the flash notice more than once
$("#flash_notice").remove();

//showing a flash message
$("#container").prepend("<div id='flash_notice'>Successfully shared the folder</div>");

//Removing the css class 'folder'
$("#folder_<%= params[:folder_id] %>").removeClass("folder");

//Adding the css class 'shared_folder'
$("#folder_<%= params[:folder_id] %>").addClass("shared_folder");