Share_Box/config/routes.rb
Rails.application.routes.draw do
  resources :folders
  resources :assets
  devise_for :users

  match "assets/get/:id" => "assets#get", as: "download",via: [:get]

  match "browse/:folder_id" => "home#browse", as: "browse",via: [:get]
  match "browse/:folder_id/new_folder" => "folders#new", as: "new_sub_folder",via: [:get,:post]
  match "browse/:folder_id/new_file" => "assets#new", :as => "new_sub_file",via: [:get,:post]

  #for renaming a folder
  match "browse/:folder_id/rename" => "folders#edit", :as => "rename_folder",via: [:get,:put]

  #for sharing the folder
  match "home/share" => "home#share",via: [:post]

  root :to => "home#index"
end

Share_Box/app/models/folder.rb
class Folder < ActiveRecord::Base
  belongs_to :user
  has_many :assets,:dependent => :destroy
  has_many :shared_folders,dependent: :destroy
  acts_as_tree

  def shared?
    !self.shared_folders.empty?
  end
end

Share_Box/app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :set_folder, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /folders
  # GET /folders.json
  def index
    @folders = current_user.folders
  end

  # GET /folders/1
  # GET /folders/1.json
  def show
  end

  # GET /folders/new
  def new
    @folder = current_user.folders.new
    if params[:folder_id]

      @current_folder = current_user.folders.find(params[:folder_id])
      @folder.parent_id = @current_folder.id
    end
  end

  # GET /folders/1/edit
  def edit
    @current_folder = @folder.parent
  end

  # POST /folders
  # POST /folders.json
  def create
    @folder = current_user.folders.new(folder_params)

    if @folder.save
      flash[:notice] = "Successfully created folder."
      if @folder.parent
        redirect_to browse_path(@folder.parent)
      else
        redirect_to root_url
      end
    else
      render :action => 'new'
    end

  end

  # PATCH/PUT /folders/1
  # PATCH/PUT /folders/1.json
  def update

    if @folder.update(folder_params)
      flash[:notice] = "Successfully Renamed folder."
      @parent_folder = @folder.parent
      if @folder.parent
        redirect_to browse_path(@folder.parent)
      else
        redirect_to root_url
      end
    else
      render :action => 'new'
    end
    # respond_to do |format|
    #   if @folder.update(folder_params)
    #     format.html { redirect_to @folder, notice: 'Folder was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @folder }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @folder.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /folders/1
  # DELETE /folders/1.json
  def destroy
    @parent_folder = @folder.parent

    @folder.destroy
    flash[:notice] = "Successfully deleted the folder and all the contents inside."
    if @parent_folder
      redirect_to browse_path(@parent_folder)
    else
      redirect_to root_url
    end

  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_folder
    if params[:folder_id]
      @folder = current_user.folders.find(params[:folder_id])
    else
      @folder = current_user.folders.find(params[:id])
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def folder_params
    params.require(:folder).permit(:name, :parent_id, :user_id)
  end
end

Share_Box/app/helpers/folders_helper.rb
module FoldersHelper
end

Share_Box/app/views/folders/_form.html.erb
<%= form_for(@folder) do |f| %>
  <% if @folder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@folder.errors.count, "error") %> prohibited this folder from being saved:</h2>

      <ul>
      <% @folder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
    <div class="field">
      <%= f.hidden_field :parent_id %><br>
    </div>
    <div class="actions">
      <% if @folder.new_record? %>
          <%= f.submit "Create Folder" %>
      <% else %>
          <%= f.submit "Rename Folder" %>
      <% end %>
    </div>
<% end %>

Share_Box/app/views/folders/edit.html.erb
<h1>Editing Folder</h1>
<%= render :partial => "home/breadcrumbs" %>
<%= render 'form' %>

<p>
  <% if @folder.parent %>
      <%= link_to "Back to '#{@folder.parent.name}' Folder", browse_path(@folder.parent) %>
  <% else %>
      <%= link_to "Back", root_url %>
  <% end %>
</p>

Share_Box/app/views/folders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Folders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Parent</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @folders.each do |folder| %>
      <tr>
        <td><%= folder.name %></td>
        <td><%= folder.parent_id %></td>
        <td><%= folder.user_id %></td>
        <td><%= link_to 'Show', folder %></td>
        <td><%= link_to 'Edit', edit_folder_path(folder) %></td>
        <td><%= link_to 'Destroy', folder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Folder', new_folder_path %>

Share_Box/app/views/folders/new.html.erb
<h1>New Folder</h1>
<%= render :partial => "home/breadcrumbs" %>
<%= render 'form' %>

<p>
  <% if @folder.parent %>
      <%= link_to "Back to '#{@folder.parent.name}' Folder", browse_path(@folder.parent) %>
  <% else %>
      <%= link_to "Back to Home page", root_url %>
  <% end %>
</p>

Share_Box/app/views/folders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @folder.name %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @folder.parent_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @folder.user_id %>
</p>

<%= link_to 'Edit', edit_folder_path(@folder) %> |
<%= link_to 'Back', folders_path %>